### ISSUE TITLE
Incompatibility with One Page Checkout

### ISSUE THREAD

**Issue by jbustamanterendon** [PrestaShopCorp/ps_checkout#192]
Good morning,

I have tried to check above that this new module does not integrate with our [One Page Checkout PS](https://addons.prestashop.com/es/proceso-rapido-compra/8503-one-page-checkout-ps-facil-rapido-e-intuitivo.html?_ga=2.156330488.290334089.1570812999-68600305.1568237835) module.

The main problem lies in the javascript code that has been placed in the file /views/templates/paypal.tpl, they have been declared constant and included the paypal sdk directly on a template, which is incorrect, for this it should be used the hookHeader and make such declarations of javascript variables and inclusions.

It is also necessary to know how a sandbox account can be associated to be able to do the integration tests better, because right now everything links to a real account and it does not give us the possibility to try the developers.

I remain attentive because it is very urgent.

Best regards.

**Comment by Quetzacoalt91** [comment]
Hi @jbustamanterendon,

To let you know, we're currently investigating on these incompatibilities with 3 one-page-checkout modules and some fixes will be dispatched with the next release.
In the meantime I'm closing all issues in this repository in order to have a single backlog.

Regards
